# workflow name
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# workflow 의 실행 동작 (각 job은 병렬 실행)
jobs:
  build: # job 이름 (build-job 등 원하는대로 변경)
  # 어느 환경에서 돌아갈 지 지정
    runs-on: ubuntu-latest

# 수행할 동작 (순서대로 수행)
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
